// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type SLA struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	TotalStorage float64 `json:"totalStorage"`
}
